function msg = nav_msgs_MapMetaDataStruct
% Message struct definition for nav_msgs/MapMetaData
coder.inline("never")
msg = struct(...
    'MessageType','nav_msgs/MapMetaData',...
    'MapLoadTime',ros_TimeStruct,...
    'Resolution',ros.internal.ros.messages.ros.default_type('single',1),...
    'Width',ros.internal.ros.messages.ros.default_type('uint32',1),...
    'Height',ros.internal.ros.messages.ros.default_type('uint32',1),...
    'Origin',geometry_msgs_PoseStruct);
coder.cstructname(msg,'nav_msgs_MapMetaDataStruct_T');
if ~isempty(coder.target)
    coder.ceval('//',coder.rref(msg));
end
end
