function msg = sensor_msgs_LaserScanStruct
% Message struct definition for sensor_msgs/LaserScan
coder.inline("never")
msg = struct(...
    'MessageType','sensor_msgs/LaserScan',...
    'Header',std_msgs_HeaderStruct,...
    'AngleMin',ros.internal.ros.messages.ros.default_type('single',1),...
    'AngleMax',ros.internal.ros.messages.ros.default_type('single',1),...
    'AngleIncrement',ros.internal.ros.messages.ros.default_type('single',1),...
    'TimeIncrement',ros.internal.ros.messages.ros.default_type('single',1),...
    'ScanTime',ros.internal.ros.messages.ros.default_type('single',1),...
    'RangeMin',ros.internal.ros.messages.ros.default_type('single',1),...
    'RangeMax',ros.internal.ros.messages.ros.default_type('single',1),...
    'Ranges',ros.internal.ros.messages.ros.default_type('single',NaN),...
    'Intensities',ros.internal.ros.messages.ros.default_type('single',NaN));
coder.cstructname(msg,'sensor_msgs_LaserScanStruct_T');
coder.varsize('msg.Ranges',[1000000000 1],[1 0]);
coder.varsize('msg.Intensities',[1000000000 1],[1 0]);
if ~isempty(coder.target)
    coder.ceval('//',coder.rref(msg));
end
end
